POST http://localhost:3001/api/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpbiIsImlkIjoiNjg3M2MyYTNiMDA0ODI1NDE1MDcxNzMzIiwiaWF0IjoxNzUyNDMyOTUwfQ.3dch_3wTBtHGSyQkzw3ADa6s0VkawCkvz9AzNoTkIk0

{
    "title": "fifth note",
    "description": "1",
    "status": "completed",
    "categories": ["work", "personal"]
}